I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 387, in script
    $ python.pause(2.0, hard=True)
  File "game/script.rpy", line 387, in <module>
    $ python.pause(2.0, hard=True)
NameError: name 'python' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 387, in script
    $ python.pause(2.0, hard=True)
  File "F:\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 387, in <module>
    $ python.pause(2.0, hard=True)
NameError: name 'python' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
ITS UTBK Simulator 1.0
Mon Apr 28 20:59:41 2025
